let data = [
  {
    Cedula: 30716524,
    Nombres: "ALAÑA FIGUEROA, JOSE ROBERTO",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31258709,
    Nombres: "ALCON LUQUEZ, WILLIAN ADRIEL",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30601545,
    Nombres: "ALVARADO COLMENAREZ, EDUARD ALEXANDER",
    Condicion: 1,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30396056,
    Nombres: "ALVAREZ ATACHO, GUSTAVO ALFONSO",
    Condicion: 1,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31047787,
    Nombres: "ARRIECHI TUA, YULIANNYS JOSE",
    Condicion: 1,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 26945225,
    Nombres: "AVENDAÑO RODRIGUEZ, YOSWER ANTONIO",
    Condicion: 2,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30105122,
    Nombres: "BARRAEZ JIMENEZ, ALEXIS MANUEL",
    Condicion: 2,
    Materia: "Programación 1 (3154)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 32023320,
    Nombres: "BARRETO MARTINEZ, ALEX JOSE",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 28382638,
    Nombres: "BENAVENTE ALEJO, STEPHANIE MARGARETH",
    Condicion: 3,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31271788,
    Nombres: "CAMACARO RODRIGUEZ, JOETH LUIS",
    Condicion: 1,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 25137790,
    Nombres: "CAMEJO REYES, ASAEL JOAS",
    Condicion: 2,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30868201,
    Nombres: "CAMPOS YEPEZ, MICHELLE CAROLINA",
    Condicion: 1,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 17034323,
    Nombres: "CARRILLO MORALES, LILIBETH LILIANA",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 20351023,
    Nombres: "CATARI MONTILLA, JOHAN ANDRES",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30004665,
    Nombres: "CHAVEZ PATIÑO, MOISES ENRIQUE",
    Condicion: 2,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30916875,
    Nombres: "CHAVEZ PEREIRA, LUIS DAVID",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31118017,
    Nombres: "CURE RIVERO, ANGEL DAVID",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 27586641,
    Nombres: "DELGADO LOVATON, SOFIA NAZARETH",
    Condicion: 2,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31366805,
    Nombres: "DIAZ HUANG, JHONN RAIKAR",
    Condicion: 1,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31972026,
    Nombres: "DOMINGUEZ MENDOZA, DIANA VALESKA",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30553694,
    Nombres: "ESCALONA COLMENARES, DANIELA ALEJANDRA",
    Condicion: 1,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31973382,
    Nombres: "ESCALONA MORALES, JESUA JAHZEEL",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30845134,
    Nombres: "ESCALONA SANGRONIS, LUIS ANGEL",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31041717,
    Nombres: "ESCALONA SILVA, JOSE DAVID",
    Condicion: 1,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30479767,
    Nombres: "FAJARDO DE LA VEGA, ALEJANDRO",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 25992343,
    Nombres: "FALCON RAMOS, ABRAHAN JOSE",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31066347,
    Nombres: "FERRER SILVA, MELANY ANDREINA",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31026165,
    Nombres: "FIGUEROA PERDOMO, DANIELA ALEJANDRA",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30844907,
    Nombres: "FLORES LEON, CARLOS ALBERTO",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30014426,
    Nombres: "FREITEZ PEREZ, FRANYELIZ CAROLINA",
    Condicion: 3,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30754077,
    Nombres: "FUENTES VALERA, MANUEL ALEJANDRO",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31099867,
    Nombres: "GARCIA GUTIERREZ, ANA KARINA",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30042305,
    Nombres: "GARCIA LOPEZ, DARIAN FABIOLA",
    Condicion: 1,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 28113561,
    Nombres: "GARCIA PIRES, JUAN ANDRES",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 29944538,
    Nombres: "GHANIM SILVA, SAID ALEJANDRO",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31368020,
    Nombres: "GIL PICHARDO, ESTEFANY PAOLA",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31766071,
    Nombres: "GIMENEZ SALAS, JOSE LEONARDO",
    Condicion: 1,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31025997,
    Nombres: "GONZALEZ SANCHEZ, RICARDO ANDRES",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 29851080,
    Nombres: "GUERRERO CRESPO, ALAN GABRIEL",
    Condicion: 2,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 28566175,
    Nombres: "GUTIERREZ GIMENEZ, GENESIS DEL CARMEN",
    Condicion: 1,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31195152,
    Nombres: "HERNANDEZ GUERRA, NELSON ANTONIO",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30325234,
    Nombres: "HERNANDEZ MENA, FERNANDO JESUS",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 29693793,
    Nombres: "HORYEN FUENTES, SOPHIA VICTORIA",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31221654,
    Nombres: "LINARES GONZALEZ, LUIS ALFONSO",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31492754,
    Nombres: "LINAREZ GOMEZ, YESSICA CAROLINA",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 29915697,
    Nombres: "LOBO RAMIREZ, CARLOS ANDRES",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30916802,
    Nombres: "LOPEZ MENDOZA, AXEL DAVID",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30894990,
    Nombres: "LUCENA LUCENA, NIXON ALEXANDER",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 28204478,
    Nombres: "LUNA BARRIOS, ORIANA VALENTINA",
    Condicion: 1,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 11427399,
    Nombres: "MARDINI CHAMI, NELLY",
    Condicion: 2,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31089011,
    Nombres: "MARQUEZ ARIAS, DANIELA SOFIA",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30353228,
    Nombres: "MARTINEZ SUAREZ, DEIVERSON ISAAC",
    Condicion: 1,
    Materia: "Programación 1 (3154)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31026972,
    Nombres: "MARTINEZ VASQUEZ, ABRAHAN JOSE",
    Condicion: 1,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30454226,
    Nombres: "MEDINA ALVARADO, CARLOS JOSE",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31401788,
    Nombres: "MEDINA APOSTOL, KEIBER JESUS",
    Condicion: 1,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30803408,
    Nombres: "MEDINA BELIZAMONT, PAOLA VALENTINA",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 27828367,
    Nombres: "MENDOZA UGEL, MARIA VALENTINA",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 28204836,
    Nombres: "MONTES TAMBO, ALBERIT MAURICIO",
    Condicion: 2,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30417042,
    Nombres: "MONTILLA MONTES, JESUS GABRIEL",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31533895,
    Nombres: "MORALES TARAZONA, JEIKER DAVID",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 16956628,
    Nombres: "MORENO VEGA, LUIS ENRIQUE",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 29896078,
    Nombres: "MORILLO RODRIGUEZ, GEOVANNY JESUS",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31535238,
    Nombres: "NAVAS VASQUEZ, JHADIEL DAVID",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31771381,
    Nombres: "OLIVERO RIVERO, VALERY CAROLINA",
    Condicion: 1,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31147057,
    Nombres: "OLIVEROS GIL, SAMUEL JOSUE",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 26831389,
    Nombres: "OLLARVES RAMOS, JORGE LUIS",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31195093,
    Nombres: "ORTEGANO HERNANDEZ, ADRIAN ALEJANDRO",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 28021112,
    Nombres: "OSAL MENDOZA, JOSMERY PAOLA",
    Condicion: 1,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30480247,
    Nombres: "OVALLES GODOY, ARIANA ELENA",
    Condicion: 1,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 16277237,
    Nombres: "PACHECO MARTINEZ, ALEXANDRA CAROLINA",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31271481,
    Nombres: "PACHECO SANCHEZ, EDWUAR JHESSUA",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30560241,
    Nombres: "PALACIOS BRICENO, FRANCISCO JAVIER",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31025923,
    Nombres: "PARADAS MENDOZA, CARLOS DAVID",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 29517195,
    Nombres: "PEÑA CASAMAYOR, MARIA VICTORIA",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 29517375,
    Nombres: "PERAZA COLMENAREZ, VALERIA ALEXANDRA",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 29517861,
    Nombres: "PERAZZO JAIMES, MARCO ANTONIO",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30995733,
    Nombres: "PEREZ AMADO, RICARDO DAVID",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30072358,
    Nombres: "PEREZ CORTEZ, ESTEFANI GABRIELA",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30803393,
    Nombres: "PEREZ MUNDARAIN, NICKOLL GISELLE",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 29795841,
    Nombres: "PEREZ PIÑERO, CRISTIAN JOSE",
    Condicion: 3,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 29831953,
    Nombres: "PERNALETE TORCATEZ, OSWMAR DANIEL",
    Condicion: 1,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31077148,
    Nombres: "PINEDA ESCALONA, WILEIDY COROMOTO",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30895054,
    Nombres: "RANGEL VASQUEZ, KAREN MARIANA",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 29805195,
    Nombres: "REIS PEREZ, MANUEL ALEJANDRO",
    Condicion: 2,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 26990816,
    Nombres: "RIVAS FRIAS, HUMBERTO GREGORIO",
    Condicion: 3,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30753633,
    Nombres: "RIVERO TORO, EMILSON GREGORIO",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31077168,
    Nombres: "RODRIGUEZ ALVARADO, MAICKOL JESUS",
    Condicion: 1,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 29795856,
    Nombres: "RODRIGUEZ RODRIGUEZ, BRAIAN JOSUE",
    Condicion: 1,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 28113260,
    Nombres: "ROMERO BENITEZ, CAREN GERALDINE",
    Condicion: 2,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31401043,
    Nombres: "ROMERO SUAREZ, CARLOS DANIEL",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 32034829,
    Nombres: "SALAS OCANDO, LIANA GABRIELA",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 29976433,
    Nombres: "SANCHEZ PEREZ, OLIVER JOSE",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 27760864,
    Nombres: "SEQUERA PARRA, JARBI ALEXANDER",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 27397444,
    Nombres: "SERRANO ARTEAGA, LUIS SEGUNDO",
    Condicion: 3,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31195126,
    Nombres: "SERRANO HERNANDEZ, OMAR DAVID",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 29778391,
    Nombres: "SIERRALTA ESCALONA, REBECA SARAHI",
    Condicion: 3,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 28493285,
    Nombres: "SIVIRA SIVIRA, JOSE ENRIQUE",
    Condicion: 2,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30266566,
    Nombres: "SOTO PAEZ, TOMAS DAVID",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30528931,
    Nombres: "SUAREZ DAZA, JOSE GABRIEL",
    Condicion: 2,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 27212680,
    Nombres: "SUAREZ MORALES, YELIMAR ANGELICA",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 27844065,
    Nombres: "TENIAS CASTELLANOS, OSCAR ALBERTO",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30454491,
    Nombres: "TORIN PARTIDAS, MOISES ABRAHAM",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31066236,
    Nombres: "TORO CASTRO, YOSGER ENRIQUE",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30657710,
    Nombres: "TOVAR PANZA, ISAIAS OCTAVIO",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 27828899,
    Nombres: "VASQUEZ LEON, CARLOS GERARDO",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 25433440,
    Nombres: "VILORIA NOGUERA, GUSTAVO ADOLFO",
    Condicion: 0,
    Materia: "Programación (C4)",
    Seccion: 1,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30255498,
    Nombres: "YEPEZ FIGUEIRA, RAY ANGEL",
    Condicion: 0,
    Materia: "Programación 1 (3154)",
    Seccion: 2,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 28204969,
    Nombres: "ZAMBRANO ROSALES, EMMANUEL JOSE",
    Condicion: 2,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 28475269,
    Nombres: "ZARAZA MENDIA, MARIANGELA JOSE",
    Condicion: 3,
    Materia: "Programación 1 (3154)",
    Seccion: 1,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30923175,
    Nombres: "ABARCA MEDINA, LISMAR DEL VALLE",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 31371339,
    Nombres: "ACOSTA GARRIDO, KRISTIAN ORLANDO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31987477,
    Nombres: "ACOSTA PACHECO, YONAIKER ALEXANDER",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30304064,
    Nombres: "AGUERO BRICEÑO, FABRIZIO ALBERTO",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31986890,
    Nombres: "ALASTRE OLLARVES, FELIPE DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31350731,
    Nombres: "ALMAO VALE, DAVID LEONARDO",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 28406661,
    Nombres: "ALVARADO ALVARADO, FERNANDO JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 25753446,
    Nombres: "ALVARADO CONTRERAS , XAVIER ALEJANDRO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31039698,
    Nombres: "ALVARADO, FRANCISCO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 32744473,
    Nombres: "ALVAREZ ALDANA, DIEGO ALEJANDRO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31018143,
    Nombres: "ALVAREZ CRESPO, ANDIMAR JOSE PAOLA",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30615337,
    Nombres: "ALVAREZ GARCIA, JOSE LEONARDO",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31987598,
    Nombres: "ALVAREZ SIVIRA, NEIKER RAFAEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 32029050,
    Nombres: "ALZURO PEREZ, LUIS ANDERSON",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30916773,
    Nombres: "ANDRADE GUZMAN, YONAIKER BAUTISTA",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 31536081,
    Nombres: "ANGELY YARESMY, RIVAS GIMENEZ",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 32254433,
    Nombres: "ARANA PERAZA, HILIMAR STEFANI",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 26380111,
    Nombres: "ARANGUREN ACOSTA, SONYER JOSUE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 32067583,
    Nombres: "ARRIETA MORA, DIEGO LEANDRO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31574734,
    Nombres: "ATACHO ALEJOS, JOSE MARIO JUNIOR",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30647426,
    Nombres: "AULAR BASTILLAS, JONATHAN ALEJANDRO",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 29805944,
    Nombres: "AZUAJE PEREZ , MIGUEL ALEJANDRO",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 30128012,
    Nombres: "BAEZ RODRIGUEZ, JONATHAN MANUEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 26577739,
    Nombres: "BARRADAS VEGA, YORAMIGABRIEL ALEXANDER",
    Condicion: 2,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 31511981,
    Nombres: "BARRIENTOS SALOM, JORGE ENRIQUE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31169367,
    Nombres: "BARRIOS QUINTERO, FABIOLA JOSEFINA",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 31802991,
    Nombres: "BELLO ELIEZ, YHANMAIBETH ANDREINA",
    Condicion: 1,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 32237183,
    Nombres: "BERMUDEZ CORDERO, VERONICA COROMOTO",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31836695,
    Nombres: "BETANCOURT RODRIGUEZ, DARWIN JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31099503,
    Nombres: "BLANCO LEON, MIGUEL DAVID",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31987506,
    Nombres: "BRACAMONTE ABADIA, GABRIEL ALEJANDRO",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 31692423,
    Nombres: "BRAVO DIAZ, LUIS DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31973205,
    Nombres: "BRAVO VASQUEZ, CHRISTOPHER GABRIEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 32067536,
    Nombres: "CAMACARO TORRES, DAYMAR LUCIANA",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31558737,
    Nombres: "CAMACHO MELENDEZ, AARON DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31146512,
    Nombres: "CAMACHO SANCHEZ, MARIA VALERIA",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 30448216,
    Nombres: "CANTILLO TORRES, NIKOL DE LOS ANGELES",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 32260326,
    Nombres: "CASTANEDA MENDOZA, AARON JAVIER",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31464228,
    Nombres: "CASTANEDA RIVERO, ALBERTO ANTONIO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31271718,
    Nombres: "CASTELLANO FIGUEROA, FRANIA YORGELIS",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 28150322,
    Nombres: "CASTILLO ALVARADO, JEANMAR IRAIDE",
    Condicion: 3,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 30590783,
    Nombres: "CASTILLO ULLOA, PEDRO JOSUE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31099520,
    Nombres: "CASTRO DELGADO, DANIEL EDUARDO",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 30288822,
    Nombres: "CELAYA GONZALEZ, EDWARD DARIO",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31925563,
    Nombres: "COLMENARES, EDUARDO ENRIQUE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 29707096,
    Nombres: "COLMENAREZ ALVAREZ, ALIRIO JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 31367908,
    Nombres: "COLMENAREZ ESCALONA, ESTHEBAN DE JESUS",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31654489,
    Nombres: "COLMENAREZ LEAL, ANGEL GABRIEL",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31026087,
    Nombres: "COLMENAREZ PEREZ, CARLOS DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30454888,
    Nombres: "CONTENTO SANCHEZ, CARLOS DANIEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 31025791,
    Nombres: "CONTRERAS , JESSICA JACCELIS",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 30325069,
    Nombres: "CORDERO FIGUEROA , ANDERSON JAVIER",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30067577,
    Nombres: "CORDERO LUNA, ANTONIO JOSE",
    Condicion: 3,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31018057,
    Nombres: "CORDERO MENDOZA, SHARAID GABRIELA",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30125368,
    Nombres: "CUICAS SOTO, OSMAR GABRIEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31662944,
    Nombres: "DAZA MATUTE, JORGE EDUARDO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30448029,
    Nombres: "DE GUGLIELMO MICELI, FABRIZZIO ANTONIO",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31900817,
    Nombres: "DELGADO GUTIERREZ, WILBER JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30676175,
    Nombres: "DESIDERIO ROJAS, MIGUEL ANDRES",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31277815,
    Nombres: "DEVIES CANELA, SEBASTIAN RAFAEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 32552294,
    Nombres: "DIAZ BRIZON, MOISES DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31277939,
    Nombres: "DUN YEPEZ, ALEJANDRO JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30849508,
    Nombres: "DURAN SUAREZ, GIOVANNY DAVID",
    Condicion: 2,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 31118078,
    Nombres: "DURAN SUAREZ, JUAN DAVID",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 30716686,
    Nombres: "ECHEVERRIA CASTRO, EDGAR ALONSO JESUS",
    Condicion: 2,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 30845208,
    Nombres: "ESCALONA ANGULO, MARIA JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 32063243,
    Nombres: "ESCALONA SALCEDO, LUIS ANGEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30979753,
    Nombres: "FARIÑA MARTINEZ, CHRISTIAN ALEJANDRO",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31454627,
    Nombres: "FIORE RAMIREZ, JEAN FRANCO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30130477,
    Nombres: "FREITEZ MENDOZA, JESUS SIMON",
    Condicion: 2,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 28604388,
    Nombres: "FREITEZ PACHECO, RICHARD GABRIEL",
    Condicion: 2,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 31557982,
    Nombres: "FRIDEBERG LUQUE, HANS ALEJANDRO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31162167,
    Nombres: "GALLARDO AGUILAR, STALIN JESUS",
    Condicion: 1,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31824993,
    Nombres: "GAONA PEREZ, KATHERINE NICOLE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 28778271,
    Nombres: "GARCIA ALVAREZ, JAIDELYS CAROLINA",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30754178,
    Nombres: "GARCIA AZUAJE, JOSE GREGORIO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31277820,
    Nombres: "GARCIA CUETO, JESUS DANIEL",
    Condicion: 2,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31277802,
    Nombres: "GARRIDO DIAZ, SERGIO DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31111398,
    Nombres: "GIMENEZ ARIAS , FABIOLA MARIA",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 27411759,
    Nombres: "GIMENEZ MOSQUERA, FRANKLIN JESUS",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31366563,
    Nombres: "GOMEZ GONZALEZ, OMAR JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31930334,
    Nombres: "GOMEZ ORTIZ, YORGELIS PAOLA",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 30559846,
    Nombres: "GOMEZ RODRIGUEZ, ORLANYS CELESTE",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31926335,
    Nombres: "GOMEZ VASQUEZ, SNAYDER ALEXANDER",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30536657,
    Nombres: "GONZALEZ CASTILLO, MAGDIELIS ISARIANNY",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 32121670,
    Nombres: "GONZALEZ HERNANDEZ, JESUS ALEJANDRO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31189177,
    Nombres: "GONZALEZ MELENDEZ, VALENTINA DEL VALLE",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31169480,
    Nombres: "GONZALEZ PEREZ, ALEJANDRO ANDRES",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 19084879,
    Nombres: "GONZALEZ RIVAS, CARLOS DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31836024,
    Nombres: "GRANADO ALVARADO, DIEGO ALFONSO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 32067178,
    Nombres: "GRATEROL BARRIOS, LUIS GUILLERMO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31137943,
    Nombres: "GUEDEZ VALBUENA, GABRIEL ALFONZO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 32646674,
    Nombres: "GUTIERREZ REVILLA, SEBASTIAN JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31271982,
    Nombres: "HERNANDEZ ALVAREZ, ADOLFO JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31877684,
    Nombres: "HERNANDEZ BASTIDAS, KATHERINE GABRIELA",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 17572989,
    Nombres: "HERNANDEZ CASANOVA, JAIME ALONSO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 32874659,
    Nombres: "HERNANDEZ CRESPO, JORGE LUIS",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31052110,
    Nombres: "HERNANDEZ GOMEZ, JEAN CARLOS",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31355397,
    Nombres: "HERNANDEZ GONZALEZ, JOSE ALEJANDRO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31366134,
    Nombres: "HERNANDEZ RUBIO, GERARDO JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 31271652,
    Nombres: "ILARRAZA GUEVARA, LUCIANO ANTONIO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30014898,
    Nombres: "JIMENEZ PINEDA, ALEXANDER JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31467523,
    Nombres: "LARA AZUAJE, YOINER EDUARDO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31161891,
    Nombres: "LEAL CAMACHO, GISSELL",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 30970501,
    Nombres: "LEAL PERDOMO, JESUS DANIEL",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 28297587,
    Nombres: "LEDEZMA SANTELIZ, ROMULO ERNESTO",
    Condicion: 1,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 28454113,
    Nombres: "LEON CARMONA, GABRIEL JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 23869091,
    Nombres: "LEON FRANCO, REYNOLD ODLANIER",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31204061,
    Nombres: "LOPEZ FERNANDEZ, WILYBETH",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 30868403,
    Nombres: "LOPEZ RODRIGUEZ, JUAN MANUEL DAVID",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30088132,
    Nombres: "LOYO SANCHEZ, ARANTXA BERENICE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30129727,
    Nombres: "LUCENA ESCALONA, ARIANNI NOHEMI",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 31558382,
    Nombres: "LUCENA REYES, JUAN FRANCISCO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31370991,
    Nombres: "LUGO PEREZ, YOALVER DANIEL",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 31169236,
    Nombres: "LUGO SUAREZ, DAVID LEOBALDO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 28644419,
    Nombres: "LUJANO SUAREZ, YEXIMAR PASTORA",
    Condicion: 3,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31493046,
    Nombres: "MARIN GONZALEZ, ROGER LUIS",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 28595190,
    Nombres: "MARTINEZ PEÑA, KEVIN JOSUE",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 29831005,
    Nombres: "MARTINEZ PEREZ, WILSON EDUARDO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31169279,
    Nombres: "MEDINA GIMENEZ, JOSE DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30995887,
    Nombres: "MELENDEZ GOMEZ, ENMANUEL ARGENIS",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 32121682,
    Nombres: "MELENDEZ REINOSO, MARCOS SEBASTIAN",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31118415,
    Nombres: "MELENDEZ REYES, ABRAHAM JOSUE",
    Condicion: 2,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31454372,
    Nombres: "MENDEZ LOPEZ, VICTOR JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31350637,
    Nombres: "MENDOZA CORTEZ, NURGENIS YUSNEIVER",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31121996,
    Nombres: "MENDOZA RANGEL, LEONEIBER JESUS",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 32121075,
    Nombres: "MENDOZA RIVAS, DASHA PAOLA",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 29995956,
    Nombres: "MENDOZA RODRIGUEZ, MARIA DANIELA",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 28779161,
    Nombres: "MENDOZA RODRIGUEZ, WALESKA ANGIBETH",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 31300923,
    Nombres: "MILAN PINEDA, EDDYMAR CAROLINA",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 28259148,
    Nombres: "MOGOLLON ARROYO, IRINA AILENNE",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 28406557,
    Nombres: "MOGOLLON CASTANEDA, KERVIN JOSE",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 30105066,
    Nombres: "MOGOLLON MENDEZ, JUAN JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31771488,
    Nombres: "MONSALVE PERAZA, ARTURO GABRIEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 32066751,
    Nombres: "MONTES HERRERA, JUNIOR DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30588363,
    Nombres: "MONTES MERCHAN, SAMUEL ALEJANDRO",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30145844,
    Nombres: "MORA CEDENO, PAOLA JOHANA",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31671639,
    Nombres: "MORA ROJAS, YHON FREDDY",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30916541,
    Nombres: "MORALES DUNO, JUAN ANDRES",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 27040756,
    Nombres: "MORENO DAZA, DANIEL ALEJANDRO",
    Condicion: 3,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31195073,
    Nombres: "NAVAS GIMENEZ, RAYMOND YORFRAN",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31802878,
    Nombres: "NELO MENDOZA, NEIBER JABDIEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 34476050,
    Nombres: "NIEVES MALDONADO, ANGEL DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 28774884,
    Nombres: "NIEVES PIÑA, CRISTIAN ALEJANDRO",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 28614560,
    Nombres: "OJEDA MARTINEZ, LEORGIMAR ANAIS",
    Condicion: 2,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 31039351,
    Nombres: "OJEDA RAMIREZ, ALBERTH LEANDRO",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31930232,
    Nombres: "OLIVAR ROMERO, CARLOS DANIEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31297491,
    Nombres: "ORTIZ AGUILAR, ANDRES GABRIEL",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31319504,
    Nombres: "ORTIZ DURAN, VALENTIN JOSUE",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 32830736,
    Nombres: "PACHECO GALLARDO, JESUS ALBERTO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 32108284,
    Nombres: "PALACIOS RONDON, ALEJANDRO JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30218835,
    Nombres: "PALMA PEREZ, CESAR AUGUSTO",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31335806,
    Nombres: "PAREDES NAVAS, ANGEL DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30509239,
    Nombres: "PARGAS GODOY, DANIELA ELIZABETH",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31877104,
    Nombres: "PARRA GONZALEZ , EDINSON JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31512003,
    Nombres: "PENA GUERRERO, MAURICIO JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31018366,
    Nombres: "PEREIRA SIVIRA, LUIS IRAIDE",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 32237270,
    Nombres: "PEREZ AGUERO, MARYORI YEBSIBEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 29916482,
    Nombres: "PEREZ ALCALA, DARIO MOISES",
    Condicion: 2,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 29976020,
    Nombres: "PEREZ CASTRO, RAFAEL ELIESER",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 29851234,
    Nombres: "PEREZ CORDERO, RAMCES ISSACAR",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31041372,
    Nombres: "PEREZ FREITEZ, SAMUEL ANDRES",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31290592,
    Nombres: "PEREZ MEDINA, ROBERT JAVIER",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 1,
    Profesor: "Gisela Parra",
  },
  {
    Cedula: 30895605,
    Nombres: "PEREZ VILLALOBOS , DUVAL ANTONIO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 32077597,
    Nombres: "PEROZO COLMENARES, ANGELO YUNEIKER",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31181756,
    Nombres: "PEROZO DIAZ, JESUS GREGORIO",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31936484,
    Nombres: "PEROZO GRATEROL, GHISELLE ANTONIETTA",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 32599356,
    Nombres: "PINEDA ALVAREZ, JUAN DIEGO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31370967,
    Nombres: "PINEDA CAMACHO, SEBASTIAN DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30676169,
    Nombres: "PINEDA RODRIGUEZ, JESUS ALEJANDRO",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 30447679,
    Nombres: "PIRE MARIN, LUIS MANUEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31544391,
    Nombres: "PRIMERA VILLALOBOS, GABRIEL ALEJANDRO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30895005,
    Nombres: "PUERTA RODRIGUEZ, KLEIDER JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31088863,
    Nombres: "QUERALES ESCALONA, SAMUEL ANTONIO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31454430,
    Nombres: "QUERALEZ RODRIGUEZ, BRANDON JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 32023494,
    Nombres: "QUIJADA CRESPO, JEREMY ANTHUAN",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31234357,
    Nombres: "RAYDER RODRIGUEZ, RAIDER JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31051762,
    Nombres: "RAYMOND CASTELLANO , DANIEL EDUARDO",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31118351,
    Nombres: "REYES PEREZ, GENESIS GABRIELA",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 27883078,
    Nombres: "REYES QUERALES, AXEL GABRIEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30304167,
    Nombres: "RIVAS PERNALETE, ANDRES EDUARDO",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 15351394,
    Nombres: "RODRIGUEZ FRANCO, OMAIRA ANALIA",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30665083,
    Nombres: "RODRIGUEZ LEAL, MARIANGEL LUCIA",
    Condicion: 2,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31770761,
    Nombres: "RODRIGUEZ LIZARDO, AARON MIGUEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 26380263,
    Nombres: "RODRIGUEZ PERNALETE, FRANKLIN JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31991372,
    Nombres: "RODRIGUEZ RODRIGUEZ, EMANUEL SYVIED",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31950597,
    Nombres: "RODRIGUEZ ROJAS , PAOLA PATRICIA",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30803656,
    Nombres: "ROJAS ALMAO, JOSE ANGEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 28778495,
    Nombres: "ROJAS PACHECO, JESUS ALEJANDRO",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 32742284,
    Nombres: "ROJAS RAGA, MASSIEL ALEJANDRA",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30420116,
    Nombres: "ROJAS RODRIGUEZ, ANDERSON JOSUE",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31448191,
    Nombres: "ROJAS SANCHEZ, LUCIANNY ESTEFANIA",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30173625,
    Nombres: "ROMERO LADINO, ALIRIO DAVID",
    Condicion: 2,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30304057,
    Nombres: "RUIZ RAMONES, ALDRI SAMUEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 29819949,
    Nombres: "SALAS OCANDO, JOSE MANUEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 25147390,
    Nombres: "SALAZAR CARUCI, FREIDYMAR PAOLA",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 30204863,
    Nombres: "SALDIVIA SALDIVIA, JOSUE MANUEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 32223880,
    Nombres: "SANCHEZ CALLES, ELIAC DE JESUS",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 32163372,
    Nombres: "SANCHEZ HURTADO, JESUS DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31141641,
    Nombres: "SANCHEZ QUERALES, NELSON JOSE",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31466711,
    Nombres: "SANCHEZ SANCHEZ, BRAYAN DANIEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 32114362,
    Nombres: "SEGUERI ESCOBAR, EMILIANNYS DANIELA",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30517704,
    Nombres: "SEGURA GALINDEZ, ROXIMAR LISSETH",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 32114982,
    Nombres: "SIVIRA ARMAS, JUAN DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 30868341,
    Nombres: "SOTELDO CHAVEZ, DARIARLIN NAZARETH",
    Condicion: 1,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30607579,
    Nombres: "SUAREZ ALVARADO, LEONARDO ANDRES",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 32224197,
    Nombres: "TERAN RODRIGUEZ, MARIA VALENTINA",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 28779048,
    Nombres: "TIMAURE ALDAZORO, BRYAN JESUS",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31319558,
    Nombres: "TOLEDO VALERA, DYLANGER",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 30125266,
    Nombres: "TORCATES QUINTERO , ADONIS GABRIEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 1,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31277935,
    Nombres: "TORREALBA TORRES, WAINNER ALEXANDER",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31558409,
    Nombres: "TORRELLAS BUERGO, MARIA FERNANDA",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31118212,
    Nombres: "TORRES ALGARA, MIGUEL DAVID",
    Condicion: 2,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31330762,
    Nombres: "TORRES FLORES, CHRISTIAN ANTONIO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 32125619,
    Nombres: "TORRES SULBARAN, JON DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31467029,
    Nombres: "TORRES TORRES, GERARDO ALFONSO",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31806093,
    Nombres: "TUA MANZANO, JHONDEIVIS WILAIKER",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 30796847,
    Nombres: "TURRA CARUCI, CAMILA VALENTINA",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31835957,
    Nombres: "URDANETA ROJAS, ISAI ALI",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 32134974,
    Nombres: "UZCATEGUI PERDOMO, CESAR NAZARETH",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 4,
    Profesor: "Olga Palma",
  },
  {
    Cedula: 31991398,
    Nombres: "VARGAS ARTEAGA, YEIKER JESUS",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31620515,
    Nombres: "VARGAS GUTIERREZ, ANGEL DAVID",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 3,
    Profesor: "Giovanni Torrealba",
  },
  {
    Cedula: 31169382,
    Nombres: "VASQUEZ APOSTOL, VALERY FABIOLA",
    Condicion: 1,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 2,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31370778,
    Nombres: "VASQUEZ, ANGELIS",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31301258,
    Nombres: "VEGAS DUNO, JOSE MIGUEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31143348,
    Nombres: "VELASQUEZ CONTRERAS, JOSUE DANIEL",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 27554375,
    Nombres: "VILLAMIZAROSAL, YASNEIDYMARIANA",
    Condicion: 2,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 3,
    Profesor: "Glennys Clemant",
  },
  {
    Cedula: 31535105,
    Nombres: "VILLANUEVA LOPEZ, ALCY TERESA",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31212704,
    Nombres: "VIRGUEZ RAMIREZ, BRAHIAM JOSUE",
    Condicion: 0,
    Materia: "Introducción a la Computación (C1)",
    Seccion: 2,
    Profesor: "Miguel Perdomo",
  },
  {
    Cedula: 31407217,
    Nombres: "ZARRAGA VASQUEZ, DANIEL ANTWAN",
    Condicion: 0,
    Materia: "Introducción a la Computación (2154)",
    Seccion: 4,
    Profesor: "Miguel Perdomo",
  },
];

export default data;
